import type { Prisma, PrismaClient } from "@prisma/client";

// Require an explicit backup policy for every generated Prisma model.
// A new model without a decision fails typecheck instead of silently disappearing.
type ModelDelegate = {
  [K in keyof PrismaClient]: PrismaClient[K] extends { findMany: unknown } ? K : never;
}[keyof PrismaClient];

// Sessions, verification tokens, account credentials and reusable two-factor
// secrets/backup codes stay out of recovery copies. Webhook idempotency evidence is
// business-critical recovery state so provider events are not applied twice
// after a restore.
export const BACKUP_MODEL_POLICY = {
  User: "user",
  Session: null,
  Account: null,
  Verification: null,
  TwoFactor: null,
  Customer: "customer",
  Referral: "referral",
  ServiceAddress: "serviceAddress",
  Lead: "lead",
  LeadNote: "leadNote",
  LeadApplianceRequest: "leadApplianceRequest",
  ApplianceType: "applianceType",
  Appliance: "appliance",
  ApplianceInspection: "applianceInspection",
  PartRecord: "partRecord",
  Supplier: "supplier",
  PurchaseOrder: "purchaseOrder",
  PurchaseOrderLineItem: "purchaseOrderLineItem",
  PurchaseOrderReceiptOperation: "purchaseOrderReceiptOperation",
  PartStockMovement: "partStockMovement",
  ApplianceCustodyEpisode: "applianceCustodyEpisode",
  RentalLineAmendment: "rentalLineAmendment",
  InspectionChecklistVersion: "inspectionChecklistVersion",
  ApplianceInspectionAmendment: "applianceInspectionAmendment",
  JobBillingHandoff: "jobBillingHandoff",
  RentalAgreement: "rentalAgreement",
  EarlyReturnResolution: "earlyReturnResolution",
  RentalLine: "rentalLine",
  ApplianceAssignment: "applianceAssignment",
  PricingRule: "pricingRule",
  SignatureRecord: "signatureRecord",
  Deposit: "deposit",
  Job: "job",
  JobAppliance: "jobAppliance",
  PendingDelivery: "pendingDelivery",
  MaintenanceRequest: "maintenanceRequest",
  Estimate: "estimate",
  EstimateLineItem: "estimateLineItem",
  Invoice: "invoice",
  InvoiceLineItem: "invoiceLineItem",
  Payment: "payment",
  Refund: "refund",
  CustomerCredit: "customerCredit",
  ProviderOperation: "providerOperation",
  SubscriptionEndIntent: "subscriptionEndIntent",
  LateReturnWaiver: "lateReturnWaiver",
  Receipt: "receipt",
  CreditApplication: "creditApplication",
  WebhookEvent: "webhookEvent",
  TaxFilingAccount: "taxFilingAccount",
  TaxJurisdiction: "taxJurisdiction",
  TaxRateVersion: "taxRateVersion",
  TaxRateObservation: "taxRateObservation",
  OfficialSourceWatch: "officialSourceWatch",
  TaxabilityRule: "taxabilityRule",
  AddressTaxLocation: "addressTaxLocation",
  AddressTaxJurisdiction: "addressTaxJurisdiction",
  InvoiceTaxLine: "invoiceTaxLine",
  CustomerTaxExemption: "customerTaxExemption",
  TaxFilingPeriod: "taxFilingPeriod",
  TaxFilingAmendment: "taxFilingAmendment",
  PurchaseUseTax: "purchaseUseTax",
  RetailDeliveryFeeRate: "retailDeliveryFeeRate",
  RetailDeliveryFeeRecord: "retailDeliveryFeeRecord",
  BusinessSettings: "businessSettings",
  MonthToMonthTermsVersion: "monthToMonthTermsVersion",
  SiteContent: "siteContent",
  SiteContentRevision: "siteContentRevision",
  SiteContentPointer: "siteContentPointer",
  DocumentArtifact: "documentArtifact",
  PrivacyRequest: "privacyRequest",
  Photo: "photo",
  ConsentRecord: "consentRecord",
  CustomerNotice: "customerNotice",
  CustomerNote: "customerNote",
  CustomerContact: "customerContact",
  StaffTask: "staffTask",
  AuditLog: "auditLog",
  LaunchSettings: "launchSettings",
  LaunchSubscriber: "launchSubscriber",
  LaunchDelivery: "launchDelivery",
  AutomationRun: "automationRun",
  SystemIssue: "systemIssue",
  SystemIssueNote: "systemIssueNote",
  MessageDelivery: "messageDelivery",
  ProviderEvent: "providerEvent",
  MarketingSuppression: "marketingSuppression",
  AssetNumberCounter: "assetNumberCounter",
} satisfies Record<Prisma.ModelName, ModelDelegate | null>;

export const BACKUP_TABLES = Object.values(BACKUP_MODEL_POLICY).filter(
  (table) => table !== null,
);
