export type AccessibilityRouteRole = "PUBLIC" | "OWNER" | "CUSTOMER" | "STAFF";

export type AccessibilityRoute = {
  /** Route template exactly as it exists under src/app. */
  path: string;
  role: AccessibilityRouteRole;
  /**
   * For automated routes this is the exact URL CI should visit.
   * For manual-only routes this names the fixture a human must prepare.
   */
  fixture: string;
  manualOnlyReason?: string;
};

export const ACCESSIBILITY_ROUTES: AccessibilityRoute[] = [
  { path: "/", role: "PUBLIC", fixture: "/" },
  { path: "/accessibility", role: "PUBLIC", fixture: "/accessibility" },
  { path: "/contact", role: "PUBLIC", fixture: "/contact" },
  { path: "/how-it-works", role: "PUBLIC", fixture: "/how-it-works" },
  { path: "/launch", role: "PUBLIC", fixture: "/launch" },
  { path: "/pricing", role: "PUBLIC", fixture: "/pricing" },
  { path: "/privacy", role: "PUBLIC", fixture: "/privacy" },
  { path: "/rent/[city]", role: "PUBLIC", fixture: "/rent/denver" },
  { path: "/service-area", role: "PUBLIC", fixture: "/service-area" },
  { path: "/terms", role: "PUBLIC", fixture: "/terms" },
  {
    path: "/estimate/[id]",
    role: "PUBLIC",
    fixture: "A real public estimate link in an isolated test database",
    manualOnlyReason:
      "The public estimate page requires a generated estimate id with a valid customer-visible state; CI does not create a stable public estimate id.",
  },
  { path: "/forgot-password", role: "PUBLIC", fixture: "/forgot-password" },
  {
    path: "/launch/confirm/[token]",
    role: "PUBLIC",
    fixture: "A newly issued launch confirmation token",
    manualOnlyReason:
      "Launch confirmation tokens are single-use and expire; a fixed token would make the accessibility test stateful and non-repeatable.",
  },
  { path: "/login", role: "PUBLIC", fixture: "/login" },
  { path: "/login/two-factor", role: "PUBLIC", fixture: "/login/two-factor" },
  { path: "/reset-password", role: "PUBLIC", fixture: "/reset-password" },
  { path: "/scan/[assetNumber]", role: "STAFF", fixture: "/scan/CI-SECURITY-UNIT" },
  {
    path: "/sign/[id]",
    role: "PUBLIC",
    fixture: "A real unsigned agreement signing link in an isolated test database",
    manualOnlyReason:
      "The signing page requires a generated agreement in a signable state; a fixed agreement id would mutate and expire across runs.",
  },

  { path: "/account", role: "CUSTOMER", fixture: "/account" },
  { path: "/account/billing", role: "CUSTOMER", fixture: "/account/billing" },
  {
    path: "/account/billing/invoice/[invoiceId]",
    role: "CUSTOMER",
    fixture: "The CI customer's generated paid invoice",
    manualOnlyReason:
      "The customer seed creates the invoice with a generated id; its authorization behavior is covered separately by customer-isolation tests.",
  },
  { path: "/account/maintenance", role: "CUSTOMER", fixture: "/account/maintenance" },
  { path: "/account/rentals", role: "CUSTOMER", fixture: "/account/rentals" },
  { path: "/account/settings", role: "CUSTOMER", fixture: "/account/settings" },
  { path: "/account/settings/privacy", role: "CUSTOMER", fixture: "/account/settings/privacy" },

  { path: "/desk/activity", role: "OWNER", fixture: "/desk/activity" },
  {
    path: "/desk/agreements/[id]/early-return",
    role: "OWNER",
    fixture: "A generated fixed-term active agreement eligible for early return",
    manualOnlyReason:
      "Eligibility depends on agreement terms and dates; the CI seed does not expose a deterministic agreement id/state for this page.",
  },
  {
    path: "/desk/agreements/[id]",
    role: "OWNER",
    fixture: "A generated rental agreement in the isolated CI database",
    manualOnlyReason:
      "The seeded agreement id is generated per run; agreement presentation and behavior have dedicated browser/integration coverage.",
  },
  { path: "/desk/agreements/new", role: "OWNER", fixture: "/desk/agreements/new" },
  { path: "/desk/agreements", role: "OWNER", fixture: "/desk/agreements" },
  { path: "/desk/automations", role: "OWNER", fixture: "/desk/automations" },
  {
    path: "/desk/billing/customer/[id]/invoice/[invoiceId]",
    role: "OWNER",
    fixture: "A generated customer and invoice pair in the isolated CI database",
    manualOnlyReason:
      "Both ids are generated by the CI customer fixture; financial isolation is covered by dedicated billing/customer-isolation tests.",
  },
  {
    path: "/desk/billing/customer/[id]",
    role: "OWNER",
    fixture: "A generated customer id in the isolated CI database",
    manualOnlyReason:
      "The customer fixture id is generated per run; the customer billing workspace has dedicated browser coverage.",
  },
  {
    path: "/desk/billing/deposits/[id]",
    role: "OWNER",
    fixture: "A generated deposit-liability row",
    manualOnlyReason:
      "This page requires a specific deposit-liability record that is not seeded with a deterministic id.",
  },
  { path: "/desk/billing/held-payments", role: "OWNER", fixture: "/desk/billing/held-payments" },
  { path: "/desk/billing", role: "OWNER", fixture: "/desk/billing" },
  { path: "/desk/billing/reconciliation", role: "OWNER", fixture: "/desk/billing/reconciliation" },
  {
    path: "/desk/customers/[id]",
    role: "OWNER",
    fixture: "A generated customer id in the isolated CI database",
    manualOnlyReason:
      "The CI customer id is generated per run; customer workspace behavior is covered by dedicated browser tests.",
  },
  { path: "/desk/customers/new", role: "OWNER", fixture: "/desk/customers/new" },
  { path: "/desk/customers", role: "OWNER", fixture: "/desk/customers" },
  { path: "/desk/dashboard", role: "OWNER", fixture: "/desk/dashboard" },
  { path: "/desk/dispatch", role: "OWNER", fixture: "/desk/dispatch" },
  { path: "/desk/driver", role: "STAFF", fixture: "/desk/driver" },
  {
    path: "/desk/estimates/[id]",
    role: "OWNER",
    fixture: "A generated estimate id",
    manualOnlyReason:
      "The estimate detail route requires a generated record and has dedicated estimate browser/integration coverage.",
  },
  { path: "/desk/estimates/new", role: "OWNER", fixture: "/desk/estimates/new" },
  { path: "/desk/estimates", role: "OWNER", fixture: "/desk/estimates" },
  { path: "/desk/fleet", role: "OWNER", fixture: "/desk/fleet" },
  { path: "/desk/growth", role: "OWNER", fixture: "/desk/growth" },
  { path: "/desk/inventory/[id]", role: "OWNER", fixture: "/desk/inventory/ci-security-appliance" },
  { path: "/desk/inventory/[id]/qr", role: "OWNER", fixture: "/desk/inventory/ci-security-appliance/qr" },
  { path: "/desk/inventory", role: "OWNER", fixture: "/desk/inventory" },
  { path: "/desk/jobs/[id]", role: "OWNER", fixture: "/desk/jobs/ci-security-job" },
  { path: "/desk/jobs/[id]/work-order", role: "OWNER", fixture: "/desk/jobs/ci-security-job/work-order" },
  { path: "/desk/jobs/new", role: "OWNER", fixture: "/desk/jobs/new" },
  { path: "/desk/jobs", role: "OWNER", fixture: "/desk/jobs" },
  { path: "/desk/launch", role: "OWNER", fixture: "/desk/launch" },
  {
    path: "/desk/leads/[id]",
    role: "OWNER",
    fixture: "A generated lead id",
    manualOnlyReason:
      "The CI seed does not create a deterministic lead id; lead detail behavior is covered by lead workflow tests.",
  },
  { path: "/desk/leads/new", role: "OWNER", fixture: "/desk/leads/new" },
  { path: "/desk/leads", role: "OWNER", fixture: "/desk/leads" },
  {
    path: "/desk/maintenance/[id]",
    role: "OWNER",
    fixture: "A generated maintenance request id",
    manualOnlyReason:
      "The CI seed does not create a deterministic maintenance-request id; request detail behavior has dedicated tests.",
  },
  { path: "/desk/maintenance", role: "OWNER", fixture: "/desk/maintenance" },
  {
    path: "/desk/notices/[id]/resolve",
    role: "OWNER",
    fixture: "A generated unresolved customer notice",
    manualOnlyReason:
      "The page requires a live unresolved notice whose state changes when resolved; fixed reusable fixture data would be unsafe.",
  },
  { path: "/desk/notices", role: "OWNER", fixture: "/desk/notices" },
  {
    path: "/desk/parts/[id]",
    role: "OWNER",
    fixture: "A generated part id",
    manualOnlyReason:
      "The CI seed does not create a deterministic part record; inventory-part behavior is covered by real-Postgres tests.",
  },
  { path: "/desk/parts", role: "OWNER", fixture: "/desk/parts" },
  { path: "/desk/privacy", role: "OWNER", fixture: "/desk/privacy" },
  {
    path: "/desk/purchase-orders/[id]",
    role: "OWNER",
    fixture: "A generated purchase order id",
    manualOnlyReason:
      "Purchase-order detail requires a generated order and mutable lifecycle state; dedicated purchasing browser tests cover it.",
  },
  { path: "/desk/purchase-orders/new", role: "OWNER", fixture: "/desk/purchase-orders/new" },
  { path: "/desk/purchase-orders", role: "OWNER", fixture: "/desk/purchase-orders" },
  { path: "/desk/reports", role: "OWNER", fixture: "/desk/reports" },
  { path: "/desk/revenue", role: "OWNER", fixture: "/desk/revenue" },
  { path: "/desk/search", role: "OWNER", fixture: "/desk/search?q=washer" },
  { path: "/desk/security/setup", role: "OWNER", fixture: "/desk/security/setup" },
  { path: "/desk/settings", role: "OWNER", fixture: "/desk/settings" },
  { path: "/desk/settings/policies", role: "OWNER", fixture: "/desk/settings/policies" },
  { path: "/desk/settings/preview-storage", role: "OWNER", fixture: "/desk/settings/preview-storage" },
  { path: "/desk/settings/website", role: "OWNER", fixture: "/desk/settings/website" },
  {
    path: "/desk/suppliers/[id]",
    role: "OWNER",
    fixture: "A generated supplier id",
    manualOnlyReason:
      "The CI seed does not create a deterministic supplier id; supplier lifecycle behavior is covered by supplier tests.",
  },
  { path: "/desk/suppliers/new", role: "OWNER", fixture: "/desk/suppliers/new" },
  { path: "/desk/suppliers", role: "OWNER", fixture: "/desk/suppliers" },
  { path: "/desk/tax/use-tax-settings", role: "OWNER", fixture: "/desk/tax/use-tax-settings" },
  { path: "/desk/tax/use-tax-worksheets", role: "OWNER", fixture: "/desk/tax/use-tax-worksheets" },
  {
    path: "/desk/tax/use-tax-worksheets/[periodId]",
    role: "OWNER",
    fixture: "A generated consumer-use-tax filing period with a valid state account",
    manualOnlyReason:
      "A current private worksheet requires a generated consumer use-tax period id; its server-side authorization and packet behavior are verified separately.",
  },
  { path: "/desk/tasks", role: "OWNER", fixture: "/desk/tasks" },
  { path: "/desk/today", role: "OWNER", fixture: "/desk/today" },
];

export function automatedAccessibilityRoutes(role?: AccessibilityRouteRole) {
  return ACCESSIBILITY_ROUTES.filter(
    (route) => !route.manualOnlyReason && (!role || route.role === role),
  );
}

export function manualAccessibilityRoutes() {
  return ACCESSIBILITY_ROUTES.filter((route) => Boolean(route.manualOnlyReason));
}
